#!/bin/sh

echo Preparing machine for template, after this it will not avialable remotely

rm -rf /root/hpr
rm -rf /root/hprdb
rm /root/*
rm /etc/hostid

pkg uninstall gnu-make git

ipadm delete-addr e1000g1/v4
ipadm delete-addr e1000g0/v4
ipadm create-addr -T dhcp e1000g0/v4
rm -rf /root/.ssh
